export const translations = {
    en: {
        // Authentication
        sources: "Sources",
        login: "Login",
        register: "Register",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        name: "Name",
        forgotPassword: "Forgot Password",
        changePassword: "Change Password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmNewPassword: "Confirm New Password",
        sendResetLink: "Send Reset Link",
        backToLogin: "Back to Login",
        resetLinkSent: "Reset link sent to your email. Please check your inbox.",
        dontHaveAccount: "Don't have an account?",
        alreadyHaveAccount: "Already have an account?",
        invalidCredentials: "Please check your credentials",
        changingPassword: "Changing Password...",
        changePasswordButton: "Change Password",
        cancel: "Cancel",
        logout: "Logout",
        passwordChanged: "Password changed successfully",
        failedToChangePassword: "Failed to change password",
        registrationFailed: "Registration failed",
        passwordsDoNotMatch: "Passwords do not match",
        emailAlreadyExists: "Email already exists",

        // Notebook
        createNotebook: "Create Notebook",
        enterNotebookName: "Enter Notebook Name",
        noNotebooks: "No notebooks yet",
        createFirstNotebook: "Create your first notebook to get started",
        noNotebooksFound: "No notebooks found. Create one above.",
        welcome: "Welcome to ThinkSync",
        loading: "Loading...",
        save: "Save",
        delete: "Delete",
        edit: "Edit",
        sources: "Sources",
        noSources: "No sources yet. Add one above.",
        creatingSource: "Creating source...",
        uploadFile: "Drag & drop files here or click to upload",
        uploading: "Uploading...",
        paste: "Paste",
        send: "Send",
        addToSources: "Add to sources",
        enterText: "Enter your text here...",
        enterNote: "Enter your note here...",
        enterWebLink: "Enter web link or YouTube link...",
        enterYoutubeLink: "Enter YouTube link...",
        supportsLinks: "Supports both web links and YouTube links",
        characters: "characters",
        maxFileSize: ", Max: 10MB",
        allowedTypes: "Allowed file types",
        editSourceTitle: "Edit Source Title",
        enterSourceTitle: "Enter source title",
        saveChanges: "Save Changes",
        copyText: "Copy Text",
        editTitle: "Edit Title",
        menu: "Menu",
        title: "Title",
        fileUpload: "File Upload",
        textInput: "Text Input",
        webLink: "Web Link",
        youtubeLink: "YouTube Link",
        addTextInput: "Add Text Input",
        supportsYoutube: "Supports YouTube links",

        // Chat
        notes: "Notes",
        addNote: "Add Note",
        chat: "Chat",
        startConversation: "Start a conversation with your sources",
        typeMessage: "Type your message...",
        selectSources: "Select sources to start chatting",
        language: "Language",
        clearChat: "Clear Chat",
        clearChatHistory: "Clear Chat History",
        clearChatConfirm: "Are you sure you want to clear all chat messages? This action cannot be undone.",
        deleting: "Deleting...",
        copyMessage: "Copy message",
        regenerateResponse: "Regenerate response",
        failedToLoadMessages: "Failed to load chat messages",
        failedToSendMessage: "Failed to send message",
        failedToAddToSources: "Failed to add to sources",
        failedToRegenerate: "Failed to regenerate response",
        failedToDeleteChat: "Failed to delete chat",

        // Landing Page
        yourAiNotebook: "Your AI-Powered Notebook",
        landingDescription: "Create, organize, and collaborate on your notes with the power of AI. Transform your ideas into actionable insights with our intelligent notebook platform.",
        smartNotebooks: "Smart Notebooks",
        smartNotebooksDesc: "Create and organize your notebooks with ease",
        aiChat: "AI Chat",
        aiChatDesc: "Interact with AI to enhance your learning",
        smartNotes: "Smart Notes",
        smartNotesDesc: "Take and organize notes efficiently",
        sourceManagement: "Source Management",
        sourceManagementDesc: "Keep track of your references and sources",

        // Error Messages
        failedToCopy: "Failed to copy to clipboard",
        failedToUpdate: "Failed to update source",
        failedToUploadFile: "Failed to upload file",
        failedToCreateTextSource: "Failed to create text source",
        failedToCreateLinkSource: "Failed to create link source",
        failedToCreateYoutubeSource: "Failed to create YouTube source",
        failedToDeleteSource: "Failed to delete source",
        failedToPaste: "Failed to paste from clipboard",
        failedToCreateNote: "Failed to create note",
        fileTypeNotSupported: "File type not supported. Please upload one of: {types}",
        fileSizeExceeded: "File size ({size}MB) exceeds 10MB limit",
        textTooLong: "Text exceeds {max} characters limit",
        noteTooLong: "Note text cannot exceed {max} characters. Current length: {current}",
        invalidUrl: "Please enter a valid URL",
        invalidYoutubeUrl: "Please enter a valid YouTube URL",
        titleCannotBeEmpty: "Title cannot be empty",
        error: "Error",
        success: "Success",
        warning: "Warning",
        info: "Info",

        // home page
        create:"Create",
        myNotebooks: "My Notebooks",
        newNotebook: "New Notebook",
        switchToListView: "Switch to List View",
        switchToGridView: "Switch to Grid View",
        createNotebookPlaceholder: "Enter notebook name",
        noNotebookYet: "No notebooks yet",
        createYourFirstNotebook: "Create your first notebook to get started",

        // Notebook Card
        open: "Open",
        edit: "Edit",
        delete: "Delete",
        save: "Save",
        cancel: "Cancel",
        moreOptions: "More options",
        created: "Created",
        noDate: "No date",
        invalidDate: "Invalid Date",
        loading: "Loading...",
    },
    fi: {
        // home page
        notes: "Muistiinpanot",
        create:"Luo",
        noNotebookYet: "Ei muistikirjoja vielä",
        createYourFirstNotebook: "Luo ensimmäinen muistikirjasi aloittaaksesi",
        myNotebooks: "Omat muistikirjat",
        newNotebook: "Uusi muistikirja",
        createNotebookPlaceholder: "Syötä muistikirjan nimi",
        switchToListView: "Vaihda luettelonäkymään",
        // Authentication
        emailAlreadyExists: "Sähköposti on jo käytössä",
        registrationFailed: "Rekisteröinti epäonnistui",
        passwordsDoNotMatch: "Salasanat eivät täsmää",
        login: "Kirjaudu",
        register: "Rekisteröidy",
        email: "Sähköposti",
        password: "Salasana",
        confirmPassword: "Vahvista salasana",
        name: "Nimi",
        forgotPassword: "Unohtuiko salasana",
        changePassword: "Vaihda salasana",
        currentPassword: "Nykyinen salasana",
        newPassword: "Uusi salasana",
        confirmNewPassword: "Vahvista uusi salasana",
        sendResetLink: "Lähetä palautuslinkki",
        backToLogin: "Takaisin kirjautumiseen",
        resetLinkSent: "Palautuslinkki lähetetty sähköpostiisi. Tarkista saapuneet.",
        dontHaveAccount: "Eikö sinulla ole tiliä?",
        alreadyHaveAccount: "Onko sinulla jo tili?",
        invalidCredentials: "Tarkista kirjautumistietosi",
        changingPassword: "Salasanaa vaihdetaan...",
        changePasswordButton: "Vaihda salasana",
        cancel: "Peruuta",
        logout: "Kirjaudu ulos",
        passwordChanged: "Salasana vaihdettu onnistuneesti",
        failedToChangePassword: "Salasanan vaihtaminen epäonnistui",

        // Notebook
        createNotebook: "Luo muistikirja",
        enterNotebookName: "Syötä muistikirjan nimi",
        noNotebooks: "Ei muistikirjoja",
        createFirstNotebook: "Luo ensimmäinen muistikirjasi aloittaaksesi",
        noNotebooksFound: "Ei muistikirjoja. Luo yksi yllä.",
        welcome: "Tervetuloa ThinkSynciin",
        loading: "Ladataan...",
        save: "Tallenna",
        delete: "Poista",
        edit: "Muokkaa",
        sources: "Lähteet",
        noSources: "Ei lähteitä. Lisää yksi yllä.",
        creatingSource: "Luodaan lähdettä...",
        uploadFile: "Vedä ja pudota tiedostoja tähän tai klikkaa ladataksesi",
        uploading: "Ladataan...",
        paste: "Liitä",
        send: "Lähetä",
        addToSources: "Lisää lähteisiin",
        enterText: "Syötä teksti tähän...",
        enterNote: "Syötä muistiinpano tähän...",
        enterWebLink: "Syötä verkkolinkki tai YouTube-linkki...",
        enterYoutubeLink: "Syötä YouTube-linkki...",
        supportsLinks: "Tukee sekä verkkolinkkejä että YouTube-linkkejä",
        characters: "merkkiä",
        maxFileSize: ", Maksimi: 10MB",
        allowedTypes: "Sallitut tiedostotyypit",
        editSourceTitle: "Muokkaa lähteen otsikkoa",
        enterSourceTitle: "Syötä lähteen otsikko",
        saveChanges: "Tallenna muutokset",
        copyText: "Kopioi teksti",
        editTitle: "Muokkaa otsikkoa",
        menu: "Valikko",
        title: "Otsikko",
        fileUpload: "Tiedoston lataus",
        textInput: "Tekstinsyöttö",
        webLink: "Verkkolinkki",
        youtubeLink: "YouTube-linkki",
        addTextInput: "Lisää tekstikenttä",
        supportsYoutube: "Tukee YouTube-linkkejä",

        // Chat
        addNote: "Lisää muistiinpano",
        chat: "Keskustelu",
        startConversation: "Aloita keskustelu lähteidesi kanssa",
        typeMessage: "Kirjoita viestisi...",
        selectSources: "Valitse lähteet aloittaaksesi keskustelun",
        language: "Kieli",
        clearChat: "Tyhjennä keskustelu",
        clearChatHistory: "Tyhjennä keskusteluhistoria",
        clearChatConfirm: "Haluatko varmasti tyhjentää kaikki keskustelut? Tätä toimintoa ei voi perua.",
        deleting: "Poistetaan...",
        copyMessage: "Kopioi viesti",
        regenerateResponse: "Uudelleenluo vastaus",
        failedToLoadMessages: "Keskustelujen lataaminen epäonnistui",
        failedToSendMessage: "Viestin lähetys epäonnistui",
        failedToAddToSources: "Lähteiden lisääminen epäonnistui",
        failedToRegenerate: "Vastauksen uudelleenluominen epäonnistui",
        failedToDeleteChat: "Keskustelun poistaminen epäonnistui",

        // Landing Page
        yourAiNotebook: "Tekoälyavusteinen muistikirjasi",
        landingDescription: "Luo, järjestä ja tee yhteistyötä muistiinpanoissasi tekoälyn avulla. Muunna ideasi toimiviksi oivalluksiksi älykkään muistikirjaalustamme avulla.",
        smartNotebooks: "Älykkäät muistikirjat",
        smartNotebooksDesc: "Luo ja järjestä muistikirjojasi helposti",
        aiChat: "Tekoälykeskustelu",
        aiChatDesc: "Keskustele tekoälyn kanssa oppimisen parantamiseksi",
        smartNotes: "Älykkäät muistiinpanot",
        smartNotesDesc: "Tee ja järjestä muistiinpanoja tehokkaasti",
        sourceManagement: "Lähdehallinta",
        sourceManagementDesc: "Pidä kirjaa viittauksistasi ja lähteistäsi",

        // Error Messages
        failedToCopy: "Leikepöydälle kopiointi epäonnistui",
        failedToUpdate: "Lähteen päivittäminen epäonnistui",
        failedToUploadFile: "Tiedoston lataus epäonnistui",
        failedToCreateTextSource: "Tekstilähteen luominen epäonnistui",
        failedToCreateLinkSource: "Linkkilähteen luominen epäonnistui",
        failedToCreateYoutubeSource: "YouTube-lähteen luominen epäonnistui",
        failedToDeleteSource: "Lähteen poistaminen epäonnistui",
        failedToPaste: "Leikepöydältä liittäminen epäonnistui",
        failedToCreateNote: "Muistiinpanon luominen epäonnistui",
        fileTypeNotSupported: "Tiedostotyyppiä ei tueta. Lataa jokin seuraavista: {types}",
        fileSizeExceeded: "Tiedoston koko ({size}MB) ylittää 10MB rajoituksen",
        textTooLong: "Teksti ylittää {max} merkin rajoituksen",
        noteTooLong: "Muistiinpanon teksti ei voi ylittää {max} merkkiä. Nykyinen pituus: {current}",
        invalidUrl: "Syötä kelvollinen URL-osoite",
        invalidYoutubeUrl: "Syötä kelvollinen YouTube-URL",
        titleCannotBeEmpty: "Otsikko ei voi olla tyhjä",
        error: "Virhe",
        success: "Onnistui",
        warning: "Varoitus",
        info: "Tieto",

        // Notebook Card
        open: "Avaa",
        edit: "Muokkaa",
        delete: "Poista",
        save: "Tallenna",
        cancel: "Peruuta",
        moreOptions: "Lisää vaihtoehtoja",
        created: "Luotu",
        sources: "lähdettä",
        noDate: "Ei päivämäärää",
        invalidDate: "Virheellinen päivämäärä",
        loading: "Ladataan...",
    }
};

// Get current language from localStorage or default to 'en'
export const getCurrentLanguage = () => {
    return localStorage.getItem('language') || 'en';
};

const capitalize = (str) =>
    str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();

// Set language in localStorage
export const setLanguage = (lang) => {
    localStorage.setItem('language', lang);
};

// Get translation for current language
export const getTranslation = (key, params = {}) => {
    const currentLang = getCurrentLanguage();
    let translation = translations[currentLang][key] || translations['en'][key] ||  capitalize(key);
    
    // Replace parameters in translation string
    Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
    });
    
    return translation;
}; 