"""Add file_path column to Source model

Revision ID: 126ad597d58d
Revises: 
Create Date: 2025-03-17 11:42:05.366562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126ad597d58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
